Added new participant text to PARTICIPANTS.md file
kortschak/git_workshop_18 pull request #17
Opened 2021-04-09 22:31 UTC by MLguilhaus

ML Guilhaus worked through the Git Workshop located at https://kortschak.io/courses/git_workshop and completed the task of making text additions to the file PARTICIPANTS.md with their workshop ID "Person 1 2021", staging and then committing these changes. Person 1 did this from their workplace, a distillery in McLaren Vale SA while the sun was rising. Person 1 also rushed their typing and made a spelling error in their new branch name.

2021-04-09 22:42 UTC, kortschak requested changes

2021-04-09 22:42 UTC, kortschak commented on PARTICIPANTS.md
> +Person 1 2021
Please leave the remainder of the file untouched change the line with your workshop ID only.

2021-04-09 23:48 UTC, MLguilhaus commented on PARTICIPANTS.md
> +Person 1 2021
Usure if it is appropriate to respond here so please let me know if email or some other alternative is better. 

I have used `git log` to find the previous commit hash to resotre it. Following this `git checkout <previous commit hash>`,  to check the hash is the one I want, and then `less` the PARTICIPANTS.md file but can only see the file as it was after I cleared all the other lines in the file. 

I also attempted `git revert <previous commit hash>` but was presented with the error message "error: Your local changes to the following files would be overwritten by merge:
	PARTICIPANTS.md
Please commit your changes or stash them before you merge.
Aborting
fatal: revert failed" 

So stashed with `git stash push --include-untracked` which I found on stack overflow (https://stackoverflow.com/questions/14318234/how-do-i-ignore-an-error-on-git-pull-about-my-local-changes-would-be-overwritt). This  was successful however appears that the PARTICIPANTS.md file is now from a commit earlier than the one I was aiming for and I am now very lost. I also have tried `git reflog` then `git revert <hash from original clone github.com:MLguilhaus/git_workshop.git>` but this does not appear to revert the PARTICIPANTS.md file to the state from that hash.

2021-04-10 01:19 UTC, kortschak commented on PARTICIPANTS.md
> +Person 1 2021
Here's fine.

This is character building for you! You *are* doing it the hard way. There are a couple of obvious ways to fix this situation, you can either revert the commit or hard reset to the previous commit. I would do a hard reset, but I'll show you both.

## Revert

The first thing to do is get your tree into a sensible state (assuming you are on the solostudnet branch).
```
$ git reset --hard # get rid of any extraneous changes — if `git status` shows no changes this can be omitted.
```
Then revert the change with
```
$ git revert HEAD
```
After this you can redo your changes and then just `git push`.

## Hard reset

Again make sure you are on the solostudnet branch and then we can get rid of the history of changes.
```
$ git reset --hard master
```
This resets the HEAD and solostudnet pointers to the commit that is the current master (i.e. where you started from). Then you can redo your changes are requested and push to GitHub. In this case though it will reject the changes unless you force it
```
$ git push -f
```

If the changes here were more involved I would do neither of these and the choice would depend on the situation.

2021-04-10 05:24 UTC, MLguilhaus commented on PARTICIPANTS.md
> +Person 1 2021
Alright, thank you, I have done this and have the output from 
`git commit -m 'Added new participant text to PARTICIPANTS.md file'` 
which is 
"[solostudnet 31d5814] Added new participant text to PARTICIPANTS.md file
 1 file changed, 1 insertion(+)" and then did `git push origin solostudnet` 

which gave 
"Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 337 bytes | 337.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:MLguilhaus/git_workshop.git
   7f20f78..31d5814  solostudnet -> solostudnet" 
   
I cannot see a new pull request but I am assuming this is because I can see the new commit in the current pull request. I think this is ok?

2021-04-10 05:31 UTC, kortschak commented on PARTICIPANTS.md
> +Person 1 2021
As an exercise in revising a PR commit, it will do. Thanks.

2021-04-10 05:31 UTC, kortschak approved these changes

2021-04-10 05:32 UTC, merged

2021-04-10 05:54 UTC, MLguilhaus commented on PARTICIPANTS.md
> +Person 1 2021
Ok. Thank you.